# Tổng quan đề tài

Bạn nhận được Cơ sở dữ liệu bóng đá châu Âu có hơn 25.000 trận đấu và hơn 10.000 cầu thủ cho các mùa bóng đá chuyên nghiệp châu Âu từ 2008 đến 2016. Mục tiêu là bạn xem qua cơ sở dữ liệu này và thực hiện phân tích, bao gồm một số bước khám phá dữ liệu, thống kê cơ bản và sau đó bạn hình dung kết quả. Để hoàn thành tất cả các bước, bạn cần truy vấn dữ liệu trong cơ sở dữ liệu bằng cách sử dụng câu lệnh SQL. Đề tài này thực hành bạn viết lệnh SQL để kéo dữ liệu về và trích xuất nó.

# Mô tả dữ liệu

Cơ sở dữ liệu bóng đá châu Âu này có hơn 25.000 trận đấu và hơn 10.000 cầu thủ cho các mùa bóng đá chuyên nghiệp châu Âu từ 2008 đến 2016, 11 quốc gia châu Âu với chức vô địch dẫn đầu. Các thuộc tính của Người chơi và Đội có nguồn gốc từ loạt trò chơi video FIFA của EA Sports, bao gồm các bản cập nhật hàng tuần.

# Gọi thư viện Python

In [2]:
#Import libraries
import numpy as np
import pandas as pd
import sqlite3
from datetime import timedelta
import warnings
warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", 100)

## Câu hỏi 1: Kết nối tới cơ sở dữ liệu và truy vấn thông tin của tất cả các bảng

Đọc https://docs.python.org/2/library/sqlite3.html

Học viên chỉ sử dụng câu lệnh SQL để truy vấn kế quả, không được sử dụng câu lệnh Pandas để tính toán ra kết quả.

In [3]:
# Kết nối với cơ sở dữ liệu
# ĐIỀN CODE VÀO ĐÂY
conn = sqlite3.connect('database.sqlite')

# Lấy thông tin của tất cả bảng
tables = pd.read_sql("""SELECT *
                        FROM sqlite_master
                        WHERE type='table';""", conn)
tables

,type,name,tbl_name,rootpage,sql
0,table,sqlite_sequence,sqlite_sequence,4,"CREATE TABLE sqlite_sequence(name,seq)"
1,table,Player_Attributes,Player_Attributes,11,"CREATE TABLE ""Player_Attributes"" (\n\t`id`\tIN..."
2,table,Player,Player,14,CREATE TABLE `Player` (\n\t`id`\tINTEGER PRIMA...
3,table,Match,Match,18,CREATE TABLE `Match` (\n\t`id`\tINTEGER PRIMAR...
4,table,League,League,24,CREATE TABLE `League` (\n\t`id`\tINTEGER PRIMA...
5,table,Country,Country,26,CREATE TABLE `Country` (\n\t`id`\tINTEGER PRIM...
6,table,Team,Team,29,"CREATE TABLE ""Team"" (\n\t`id`\tINTEGER PRIMARY..."
7,table,Team_Attributes,Team_Attributes,2,CREATE TABLE `Team_Attributes` (\n\t`id`\tINTE...

## Câu hỏi 2: Liệt kê các quốc gia có trong dữ liệu bảng "Country"

In [4]:
# ĐIỀN CODE VÀO ĐÂY
result = pd.read_sql("SELECT * FROM Country", conn)
result

       id         name
0       1      Belgium
1    1729      England
2    4769       France
3    7809      Germany
4   10257        Italy
5   13274  Netherlands
6   15722       Poland
7   17642     Portugal
8   19694     Scotland
9   21518        Spain
10  24558  Switzerland

## Câu hỏi 3: Liệt kê các giải đấu trong bảng "League"

In [6]:
# ĐIỀN CODE VÀO ĐÂY
result = pd.read_sql("SELECT name FROM League;", conn)
result

                        name
0     Belgium Jupiler League
1     England Premier League
2             France Ligue 1
3      Germany 1. Bundesliga
4              Italy Serie A
5     Netherlands Eredivisie
6         Poland Ekstraklasa
7   Portugal Liga ZON Sagres
8    Scotland Premier League
9            Spain LIGA BBVA
10  Switzerland Super League

## Câu hỏi 4: Liệt kê các giải đấu và thông tin quốc gia của từng league

Bảng League có quan hệ với bảng Country qua khóa country_id.

In [ ]:
# ĐIỀN CODE VÀO ĐÂY
result = pd.read_sql("SELECT L.*, C.name AS country_name " \
                     "FROM League L " \
                     "JOIN Country C ON L.country_id = C.id", conn)
result

       id  country_id                      name country_name
0       1           1    Belgium Jupiler League      Belgium
1    1729        1729    England Premier League      England
2    4769        4769            France Ligue 1       France
3    7809        7809     Germany 1. Bundesliga      Germany
4   10257       10257             Italy Serie A        Italy
5   13274       13274    Netherlands Eredivisie  Netherlands
6   15722       15722        Poland Ekstraklasa       Poland
7   17642       17642  Portugal Liga ZON Sagres     Portugal
8   19694       19694   Scotland Premier League     Scotland
9   21518       21518           Spain LIGA BBVA        Spain
10  24558       24558  Switzerland Super League  Switzerland

## Câu hỏi 5: Liệt kê các trận đấu trong bảng  “Match”
- Khi một đội là chủ nhà, đội đó là "home team". Đội còn lại là "away team"
- Trong bảng Match, mỗi dòng dư liệu là một trận đấu của một đội chủ nhà và đội khách, tương ứng với kết quả ghi bàn đội nhà (home goal) và đội khách (away goal).

In [ ]:
# ĐIỀN CODE VÀO ĐÂY
result = pd.read_sql("SELECT *,  " \
                     "FROM Match", conn)
result

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,home_player_X1,home_player_X2,home_player_X3,home_player_X4,home_player_X5,home_player_X6,home_player_X7,home_player_X8,home_player_X9,home_player_X10,home_player_X11,away_player_X1,away_player_X2,away_player_X3,away_player_X4,away_player_X5,away_player_X6,away_player_X7,away_player_X8,away_player_X9,away_player_X10,away_player_X11,home_player_Y1,home_player_Y2,home_player_Y3,home_player_Y4,home_player_Y5,home_player_Y6,home_player_Y7,home_player_Y8,home_player_Y9,home_player_Y10,home_player_Y11,away_player_Y1,away_player_Y2,away_player_Y3,away_player_Y4,away_player_Y5,away_player_Y6,...,home_player_11,away_player_1,away_player_2,away_player_3,away_player_4,away_player_5,away_player_6,away_player_7,away_player_8,away_player_9,away_player_10,away_player_11,goal,shoton,shotoff,foulcommit,card,cross,corner,possession,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,LBH,LBD,LBA,PSH,PSD,PSA,WHH,WHD,WHA,SJH,SJD,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,1.73,3.40,5.00,1.75,3.35,4.20,1.85,3.2,3.5,1.80,3.3,3.75,NaN,NaN,NaN,1.70,3.30,4.33,1.90,3.3,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,1.95,3.20,3.60,1.80,3.30,3.95,1.90,3.2,3.5,1.90,3.2,3.50,NaN,NaN,NaN,1.83,3.30,3.60,1.95,3.3,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,2.38,3.30,2.75,2.40,3.30,2.55,2.60,3.1,2.3,2.50,3.2,2.50,NaN,NaN,NaN,2.50,3.25,2.40,2.63,3.3,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,1.44,3.75,7.50,1.40,4.00,6.80,1.40,3.9,6.0,1.44,3.6,6.50,NaN,NaN,NaN,1.44,3.75,6.00,1.44,4.0,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,5.00,3.50,1.65,5.00,3.50,1.60,4.00,3.3,1.7,4.00,3.4,1.72,NaN,NaN,NaN,4.20,3.40,1.70,4.50,3.5,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25974,25975,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992091,10190,10191,1,0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,1.0,3.0,3.0,3.0,3.0,6.0,...,195215.0,462944.0,563066.0,8800.0,67304.0,158253.0,133126.0,186524.0,93223.0,121115.0,232110.0,289732.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25975,25976,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992092,9824,10199,1,2,1.0,3.0,5.0,7.0,2.0,4.0,6.0,8.0,5.0,4.0,6.0,1.0,2.0,4.0,6.0,8.0,3.0,5.0,7.0,3.0,5.0,7.0,1.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,9.0,11.0,11.0,1.0,3.0,3.0,3.0,3.0,7.0,...,37257.0,42276.0,114792.0,150007.0,178119.0,27232.0,570830.0,260708.0,201704.0,36382.0,34082.0,95257.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25976,25977,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992093,9956,10179,2,0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,1.0,3.0,3.0,3.0,3.0,6.0,...,289472.0,10637.0,67349.0,202663.0,32597.0,114794.0,188114.0,25840.0,482200.0,95230.0,451335.0,275122.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25977,25978,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992094,7896,10243,0,0,1.0,2.0,4.0,6.0,8.0,3.0,7.0,5.0,3.0,5.0,7.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,10.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,6.0,...,178142.0,274776.0,121080.0,197757.0,260964.0,231614.0,113235.0,41116.0,462608.0,42262.0,92252.0,194532.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25978,25979,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992095,10192,9931,4,3,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,4.0,6.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,6.0,...,71764.0,156175.0,95216.0,172768.0,22834.0,458806.0,207234.0,25772.0,40274.0,34035.0,41726.0,527103.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Câu hỏi 6: Liệt kê các trận đấu và thông tin về leage và country tương ứng

Bảng Match có quan hệ với :
 - Bảng Country thông qua khóa country_id
 - Bảng League thông qua khóa League_id
 
Sử dụng câu lệnh join để kết nối dư liệu từ 3 bảng trên.

In [ ]:
# ĐIỀN CODE VÀO ĐÂY
result = pd.read_sql("SELECT M.*, L.name AS league_name, C.name AS country_name " \
                     "FROM Match M " \
                     "JOIN League L ON M.league_id = L.id " \
                     "JOIN Country C ON L.country_id = C.id", conn)
result

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,home_player_X1,home_player_X2,home_player_X3,home_player_X4,home_player_X5,home_player_X6,home_player_X7,home_player_X8,home_player_X9,home_player_X10,home_player_X11,away_player_X1,away_player_X2,away_player_X3,away_player_X4,away_player_X5,away_player_X6,away_player_X7,away_player_X8,away_player_X9,away_player_X10,away_player_X11,home_player_Y1,home_player_Y2,home_player_Y3,home_player_Y4,home_player_Y5,home_player_Y6,home_player_Y7,home_player_Y8,home_player_Y9,home_player_Y10,home_player_Y11,away_player_Y1,away_player_Y2,away_player_Y3,away_player_Y4,away_player_Y5,away_player_Y6,...,away_player_2,away_player_3,away_player_4,away_player_5,away_player_6,away_player_7,away_player_8,away_player_9,away_player_10,away_player_11,goal,shoton,shotoff,foulcommit,card,cross,corner,possession,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,LBH,LBD,LBA,PSH,PSD,PSA,WHH,WHD,WHA,SJH,SJD,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA,league_name,country_name
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,1.73,3.40,5.00,1.75,3.35,4.20,1.85,3.2,3.5,1.80,3.3,3.75,NaN,NaN,NaN,1.70,3.30,4.33,1.90,3.3,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20,Belgium Jupiler League,Belgium
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,1.95,3.20,3.60,1.80,3.30,3.95,1.90,3.2,3.5,1.90,3.2,3.50,NaN,NaN,NaN,1.83,3.30,3.60,1.95,3.3,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60,Belgium Jupiler League,Belgium
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,2.38,3.30,2.75,2.40,3.30,2.55,2.60,3.1,2.3,2.50,3.2,2.50,NaN,NaN,NaN,2.50,3.25,2.40,2.63,3.3,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75,Belgium Jupiler League,Belgium
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,1.44,3.75,7.50,1.40,4.00,6.80,1.40,3.9,6.0,1.44,3.6,6.50,NaN,NaN,NaN,1.44,3.75,6.00,1.44,4.0,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50,Belgium Jupiler League,Belgium
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,5.00,3.50,1.65,5.00,3.50,1.60,4.00,3.3,1.7,4.00,3.4,1.72,NaN,NaN,NaN,4.20,3.40,1.70,4.50,3.5,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67,Belgium Jupiler League,Belgium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25974,25975,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992091,10190,10191,1,0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,1.0,3.0,3.0,3.0,3.0,6.0,...,563066.0,8800.0,67304.0,158253.0,133126.0,186524.0,93223.0,121115.0,232110.0,289732.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Switzerland Super League,Switzerland
25975,25976,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992092,9824,10199,1,2,1.0,3.0,5.0,7.0,2.0,4.0,6.0,8.0,5.0,4.0,6.0,1.0,2.0,4.0,6.0,8.0,3.0,5.0,7.0,3.0,5.0,7.0,1.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,9.0,11.0,11.0,1.0,3.0,3.0,3.0,3.0,7.0,...,114792.0,150007.0,178119.0,27232.0,570830.0,260708.0,201704.0,36382.0,34082.0,95257.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Switzerland Super League,Switzerland
25976,25977,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992093,9956,10179,2,0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,1.0,3.0,3.0,3.0,3.0,6.0,...,67349.0,202663.0,32597.0,114794.0,188114.0,25840.0,482200.0,95230.0,451335.0,275122.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Switzerland Super League,Switzerland
25977,25978,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992094,7896,10243,0,0,1.0,2.0,4.0,6.0,8.0,3.0,7.0,5.0,3.0,5.0,7.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,10.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,6.0,...,121080.0,197757.0,260964.0,231614.0,113235.0,41116.0,462608.0,42262.0,92252.0,194532.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Switzerland Super League,Switzerland
25978,25979,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992095,10192,9931,4,3,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,4.0,6.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,6.0,...,95216.0,172768.0,22834.0,458806.0,207234.0,25772.0,40274.0,34035.0,41726.0,527103.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Switzerland Super League,Switzerland

## Câu hỏi 7: Liệt kê số lượng trận đấu của mỗi giải đấu bao gồm cả tên giải đấu, sắp xếp theo thứ tự giảm dần số trận đấu

In [ ]:
# ĐIỀN CODE VÀO ĐÂY
result = pd.read_sql("SELECT L.name AS League_name, COUNT(M.id) AS Total_matches " \
                     "FROM Match M " \
                     "JOIN League L ON M.league_id = L.id " \
                     "GROUP BY L.id " \
                     "ORDER BY total_matches DESC", conn)
result

                 League_name  Total_matches
0            Spain LIGA BBVA           3040
1             France Ligue 1           3040
2     England Premier League           3040
3              Italy Serie A           3017
4     Netherlands Eredivisie           2448
5      Germany 1. Bundesliga           2448
6   Portugal Liga ZON Sagres           2052
7         Poland Ekstraklasa           1920
8    Scotland Premier League           1824
9     Belgium Jupiler League           1728
10  Switzerland Super League           1422

## Câu hỏi 8: Liệt kê tổng số bàn thắng của đội nhà và đội khách trong mỗi giải đấu
- Sử dụng câu lệnh Group By

In [19]:
# ĐIỀN CODE VÀO ĐÂY
result = pd.read_sql("SELECT L.name AS league_name, " \
                        "SUM(M.home_team_goal) AS total_home_goals, " \
                        "SUM(M.away_team_goal) AS total_away_goals " \
                    "FROM Match M " \
                    "JOIN League L ON M.league_id = L.id " \
                    "GROUP BY L.id", conn)
result

                 league_name  total_home_goals  total_away_goals
0     Belgium Jupiler League              2781              2060
1     England Premier League              4715              3525
2             France Ligue 1              4265              3162
3      Germany 1. Bundesliga              3982              3121
4              Italy Serie A              4528              3367
5     Netherlands Eredivisie              4357              3185
6         Poland Ekstraklasa              2678              1978
7   Portugal Liga ZON Sagres              2890              2311
8    Scotland Premier League              2607              2197
9            Spain LIGA BBVA              4959              3453
10  Switzerland Super League              2365              1801

## Câu hỏi 9: Liệt kê thông tin các đội từ bảng “Team”

In [20]:
# ĐIỀN CODE VÀO ĐÂY
result = pd.read_sql("SELECT * FROM Team", conn)
result

        id  team_api_id  team_fifa_api_id      team_long_name team_short_name
0        1         9987             673.0            KRC Genk             GEN
1        2         9993             675.0        Beerschot AC             BAC
2        3        10000           15005.0    SV Zulte-Waregem             ZUL
3        4         9994            2007.0    Sporting Lokeren             LOK
4        5         9984            1750.0   KSV Cercle Brugge             CEB
..     ...          ...               ...                 ...             ...
294  49479        10190             898.0       FC St. Gallen             GAL
295  49837        10191            1715.0             FC Thun             THU
296  50201         9777             324.0         Servette FC             SER
297  50204         7730            1862.0  FC Lausanne-Sports             LAU
298  51606         7896               NaN              Lugano             LUG

[299 rows x 5 columns]

## Câu hỏi 10: Liệt kê 20 đội với số bàn thắng sân nhà cao nhất
- Sử dung câu lênh GROUP BY, LIMIT

In [21]:
# ĐIỀN CODE VÀO ĐÂY
result = pd.read_sql("SELECT T.team_long_name, " \
                        "SUM(M.home_team_goal) AS home_goals " \
                    "FROM Team T " \
                    "JOIN Match M ON T.team_api_id = M.home_team_api_id " \
                    "GROUP BY T.team_api_id " \
                    "ORDER BY home_goals DESC LIMIT 20", conn)
result

         team_long_name  home_goals
0        Real Madrid CF         505
1          FC Barcelona         495
2                Celtic         389
3      FC Bayern Munich         382
4                   PSV         370
5       Manchester City         365
6                  Ajax         360
7              FC Basel         344
8     Manchester United         338
9               Chelsea         333
10  Paris Saint-Germain         332
11      Atlético Madrid         321
12           SL Benfica         321
13       BSC Young Boys         319
14             Juventus         307
15              Arsenal         306
16               Napoli         303
17          Valencia CF         299
18                 Roma         299
19    Borussia Dortmund         298

## Câu hỏi 11: Liệt kê 20 đội có số bàn thắng trên sân khách cao nhất
- Sử dụng câu lênh GROUP BY, LIMIT

In [22]:
# ĐIỀN CODE VÀO ĐÂY
result = pd.read_sql("SELECT T.team_long_name, " \
                        "SUM(M.away_team_goal) AS away_goals " \
                    "FROM Team T " \
                    "JOIN Match M ON T.team_api_id = M.away_team_api_id " \
                    "GROUP BY T.team_api_id " \
                    "ORDER BY away_goals DESC LIMIT 20", conn)
result

         team_long_name  away_goals
0          FC Barcelona         354
1        Real Madrid CF         338
2                Celtic         306
3                  Ajax         287
4                   PSV         282
5              FC Basel         275
6      FC Bayern Munich         271
7               Arsenal         267
8     Borussia Dortmund         253
9               Chelsea         250
10           SL Benfica         247
11             FC Porto         246
12    Manchester United         244
13      Manchester City         241
14            Liverpool         237
15             Juventus         236
16  Paris Saint-Germain         236
17                 Roma         231
18            FC Zürich         227
19    Tottenham Hotspur         226

## Câu hỏi 12: Liệt kê tên các đội bóng và tổng số bàn thắng mỗi đội, sắp xếp  theo số lượng giảm dần

- Tổng số bàn thắng của một đội bao gồm cả số bàn thắng ở sân nhà và sân khách.
- Sử dụng câu lệnh Union

In [26]:
# ĐIỀN CODE VÀO ĐÂY
result = pd.read_sql("SELECT T.team_long_name, " \
                        "SUM(goals) AS total_goals " \
                    "FROM ( SELECT M.home_team_api_id AS team_id, M.home_team_goal AS goals " \
                            "FROM Match M " \
                            "UNION " \
                            "SELECT M.away_team_api_id AS team_id, M.away_team_goal AS goals " \
                            "FROM Match M ) " \
                    "AS G " \
                    "JOIN Team T ON T.team_api_id = G.team_id " \
                    "GROUP BY T.team_api_id " \
                    "ORDER BY total_goals DESC", conn)
result

            team_long_name  total_goals
0           Real Madrid CF           55
1         FC Bayern Munich           45
2                   Celtic           45
3                      PSV           38
4                  Chelsea           36
..                     ...          ...
294        SV Darmstadt 98            3
295            Le Havre AC            3
296                Pescara            3
297  DSC Arminia Bielefeld            3
298                Amadora            3

[299 rows x 2 columns]

## Câu hỏi 13: Liệt kê tên các đội bóng (long name) và tổng số trận đấu đội đó tham gia, sắp xếp theo thứ tự giảm dần.

In [ ]:
# ĐIỀN CODE VÀO ĐÂY
result = pd.read_sql("SELECT T.team_long_name, " \
                        "COUNT(M.id) AS matches_played " \
                     "FROM Team T " \
                     "LEFT JOIN Match M  ON T.team_api_id = M.home_team_api_id  OR T.team_api_id = M.away_team_api_id " \
                     "GROUP BY T.team_api_id " \
                     "ORDER BY matches_played DESC", conn)
result

                   team_long_name  matches_played
0                      Sevilla FC             304
1                       Getafe CF             304
2         Athletic Club de Bilbao             304
3                         Chelsea             304
4                 Manchester City             304
..                            ...             ...
294                     KAS Eupen              30
295                      Trofense              30
296                  Portimonense              30
297                       Amadora              30
298  Termalica Bruk-Bet Nieciecza              30

[299 rows x 2 columns]

## Câu hỏi 14: Liệt kê số trận thắng, thua và hòa của mỗi đội.

- Nếu một đội có số lượng bàn thắng trên sân nhà > số lượng bàn thắng trên sân khách của chính đội đó, thì đội đó sẽ "thắng" trong trận đấu này
- Nếu một đội có số lượng bàn thắng trên sân nhà < số lượng bàn thắng trên sân khách của chính đội đó, thì đội đó sẽ "thua" trong trận đấu này
- Nếu một đội có số lượng bàn thắng trên sân nhà = số lượng bàn thắng trên sân khách của chính đội đó, thì đội đó sẽ "hòa" trong trận đấu này
- Sử dụng câu lệnh "Case When"

In [36]:
# ĐIỀN CODE VÀO ĐÂY
query = """
SELECT 
    T.team_long_name,
    SUM(
      CASE
        WHEN M.home_team_api_id = T.team_api_id AND M.home_team_goal  > M.away_team_goal THEN 1
        WHEN M.away_team_api_id = T.team_api_id AND M.away_team_goal  > M.home_team_goal THEN 1
        ELSE 0
      END
    ) AS wins,
    SUM(
      CASE
        WHEN M.home_team_api_id = T.team_api_id AND M.home_team_goal  < M.away_team_goal THEN 1
        WHEN M.away_team_api_id = T.team_api_id AND M.away_team_goal  < M.home_team_goal THEN 1
        ELSE 0
      END
    ) AS losses,
    SUM(
      CASE
        WHEN (M.home_team_api_id = T.team_api_id OR M.away_team_api_id = T.team_api_id)
             AND M.home_team_goal = M.away_team_goal
        THEN 1 ELSE 0
      END
    ) AS draws
FROM Team T
LEFT JOIN "Match" M
  ON T.team_api_id = M.home_team_api_id
  OR T.team_api_id = M.away_team_api_id
GROUP BY T.team_api_id
ORDER BY wins DESC;
"""

# chạy và xem kết quả
result = pd.read_sql(query, conn)
result

            team_long_name  wins  losses  draws
0             FC Barcelona   234      27     43
1           Real Madrid CF   228      40     36
2                   Celtic   218      36     50
3         FC Bayern Munich   193      35     44
4        Manchester United   192      55     57
..                     ...   ...     ...    ...
294           FC Dordrecht     4      22      8
295   SpVgg Greuther Fürth     4      21      9
296  DSC Arminia Bielefeld     4      14     16
297             Córdoba CF     3      24     11
298       AC Arles-Avignon     3      24     11

[299 rows x 4 columns]

## Câu hỏi 15: Liệt kê 10 đội có số trận thắng nhiều nhất

In [ ]:
# ĐIỀN CODE VÀO ĐÂY
query15 = """
SELECT * FROM (
    SELECT 
        T.team_long_name,
        SUM(CASE 
            WHEN M.home_team_api_id = T.team_api_id AND M.home_team_goal > M.away_team_goal THEN 1
            WHEN M.away_team_api_id = T.team_api_id AND M.away_team_goal > M.home_team_goal THEN 1
            ELSE 0 END) AS wins
    FROM Team T
    LEFT JOIN Match M 
      ON T.team_api_id = M.home_team_api_id OR T.team_api_id = M.away_team_api_id
    GROUP BY T.team_api_id
) ORDER BY wins DESC
LIMIT 10;
"""

# chạy và xem kết quả
result = pd.read_sql(query15, conn)
result

      team_long_name  wins
0       FC Barcelona   234
1     Real Madrid CF   228
2             Celtic   218
3   FC Bayern Munich   193
4  Manchester United   192
5           Juventus   189
6         SL Benfica   185
7           FC Porto   183
8               Ajax   181
9           FC Basel   180

## Câu hỏi 16: Liệt kê tỉ lệ phần trăm về số trận của mỗi giải trên tổng tất cả các trận

In [38]:
# ĐIỀN CODE VÀO ĐÂY
result = pd.read_sql("SELECT L.name, " \
                        "COUNT(M.id) * 100.0 / (SELECT COUNT(*) FROM Match) AS percent_matches " \
                     "FROM Match M " \
                     "JOIN League L ON M.league_id = L.id " \
                     "GROUP BY L.id;", conn)
result

                        name  percent_matches
0     Belgium Jupiler League         6.651526
1     England Premier League        11.701759
2             France Ligue 1        11.701759
3      Germany 1. Bundesliga         9.422995
4              Italy Serie A        11.613226
5     Netherlands Eredivisie         9.422995
6         Poland Ekstraklasa         7.390585
7   Portugal Liga ZON Sagres         7.898687
8    Scotland Premier League         7.021055
9            Spain LIGA BBVA        11.701759
10  Switzerland Super League         5.473652

## Câu hỏi 17: Liệt kê tỉ lệ phần trăm về số bàn ghi được của từng giải so với tổng số bàn của tất cả các trận.

In [39]:
# ĐIỀN CODE VÀO ĐÂY
result = pd.read_sql("SELECT L.name, (SUM(M.home_team_goal + M.away_team_goal)) * 100.0 /  (SELECT SUM(home_team_goal + away_team_goal) FROM Match) AS percent_goals " \
                     "FROM Match M " \
                     "JOIN League L ON M.league_id = L.id " \
                     "GROUP BY L.id;", conn)
result

                        name  percent_goals
0     Belgium Jupiler League       6.887476
1     England Premier League      11.723363
2             France Ligue 1      10.566677
3      Germany 1. Bundesliga      10.105709
4              Italy Serie A      11.232518
5     Netherlands Eredivisie      10.730292
6         Poland Ekstraklasa       6.624269
7   Portugal Liga ZON Sagres       7.399661
8    Scotland Premier League       6.834834
9            Spain LIGA BBVA      11.968074
10  Switzerland Super League       5.927127

## Câu hỏi 18: Liệt kê tổng số bàn ghi được của từng giải đấu theo từng mùa giải.

In [40]:
# ĐIỀN CODE VÀO ĐÂY
result = pd.read_sql("SELECT L.name AS league_name, M.season, " \
                        "SUM(M.home_team_goal + M.away_team_goal) AS total_goals " \
                     "FROM Match M JOIN League L ON M.league_id = L.id GROUP BY L.id, M.season " \
                     "ORDER BY M.season, league_name;", conn)
result

                 league_name     season  total_goals
0     Belgium Jupiler League  2008/2009          855
1     England Premier League  2008/2009          942
2             France Ligue 1  2008/2009          858
3      Germany 1. Bundesliga  2008/2009          894
4              Italy Serie A  2008/2009          988
..                       ...        ...          ...
83        Poland Ekstraklasa  2015/2016          635
84  Portugal Liga ZON Sagres  2015/2016          831
85   Scotland Premier League  2015/2016          650
86           Spain LIGA BBVA  2015/2016         1043
87  Switzerland Super League  2015/2016          566

[88 rows x 3 columns]

## Câu hỏi 19: Liệt kê thông tin cầu thủ:

- Quy đổi cân nặng sang kilogram
- Quy đổi chiều cao sang mét
- Tính chỉ số bmi = ( (weight* 0.453592) / (height/100)^2)
- Tính tuổi của cầu thủ

In [41]:
# ĐIỀN CODE VÀO ĐÂY
result = pd.read_sql("SELECT P.player_name, " \
                     "P.birthday, "
                     "(P.weight * 0.453592) AS weight_kg, "
                     "(P.height / 100.0) AS height_m, "
                     "(P.weight * 0.453592) / ((P.height / 100.0) * (P.height / 100.0)) AS BMI, "
                     "(CAST(strftime('%Y', 'now') AS INT) - CAST(strftime('%Y', P.birthday) AS INT)) AS age " \
                     "FROM Player P;", conn)
result

,player_name,birthday,weight_kg,height_m,BMI,age
0,Aaron Appindangoye,1992-02-29 00:00:00,84.821704,1.8288,25.361478,33
1,Aaron Cresswell,1989-12-15 00:00:00,66.224432,1.7018,22.866579,36
2,Aaron Doran,1991-05-13 00:00:00,73.935496,1.7018,25.529126,34
3,Aaron Galindo,1982-05-08 00:00:00,89.811216,1.8288,26.853330,43
4,Aaron Hughes,1979-11-08 00:00:00,69.853168,1.8288,20.885923,46
...,...,...,...,...,...,...
11055,Zoumana Camara,1979-04-03 00:00:00,76.203456,1.8288,22.784644,46
11056,Zsolt Laczko,1986-12-18 00:00:00,79.832192,1.8288,23.869627,39
11057,Zsolt Low,1979-04-29 00:00:00,69.853168,1.8034,21.478402,46
11058,Zurab Khizanishvili,1981-10-06 00:00:00,78.017824,1.8542,22.692413,44
11059,Zvjezdan Misimovic,1982-06-05 00:00:00,79.832192,1.8034,24.546746,43

## Câu hỏi 20: Liệt kê cầu thủ lớn tuổi nhất

In [42]:
# ĐIỀN CODE VÀO ĐÂY
result = pd.read_sql("SELECT player_name, birthday " \
                     "FROM Player " \
                     "ORDER BY birthday ASC LIMIT 1;", conn)
result

       player_name             birthday
0  Alberto Fontana  1967-01-23 00:00:00

## Câu hỏi 21: Liệt kê  cầu thủ có số trận đấu nhiều nhất

In [43]:
# ĐIỀN CODE VÀO ĐÂY
query21 = """
SELECT P.player_name,
       COUNT(M.id) AS matches_played
FROM Player P
JOIN Player_Attributes PA ON P.player_api_id = PA.player_api_id
JOIN Match M 
   ON P.player_api_id IN (
        M.home_player_1, M.home_player_2, M.home_player_3, M.home_player_4, M.home_player_5,
        M.home_player_6, M.home_player_7, M.home_player_8, M.home_player_9, M.home_player_10, M.home_player_11,
        M.away_player_1, M.away_player_2, M.away_player_3, M.away_player_4, M.away_player_5,
        M.away_player_6, M.away_player_7, M.away_player_8, M.away_player_9, M.away_player_10, M.away_player_11
    )
GROUP BY P.player_api_id
ORDER BY matches_played DESC
LIMIT 1;
"""

# chạy và xem kết quả
result = pd.read_sql(query21, conn)
result

         player_name  matches_played
0  Claudio Marchisio           11448

## Câu hỏi 22: Liệt kê các cầu thủ có tổng số điểm đánh giá lớn hơn 80

In [45]:
# ĐIỀN CODE VÀO ĐÂY
result = pd.read_sql("SELECT P.player_name, " \
                        "SUM(PA.overall_rating) AS total_rating " \
                     "FROM Player P " \
                     "JOIN Player_Attributes PA ON P.player_api_id = PA.player_api_id " \
                     "GROUP BY P.player_api_id HAVING total_rating > 80;", conn)
result

             player_name  total_rating
0      Patryk Rachwal,18           842
1            Diego Mainz          1457
2            Jose Dorado          1455
3       Ignacio Gonzalez          1067
4            Alberto Rey           351
...                  ...           ...
11055        Greg Taylor           571
11056   Francisco Afonso           118
11057     Fynn Arkenberg           116
11058     Rees Greenwood           508
11059  Alexandre Azevedo           116

[11060 rows x 2 columns]